[tox]
envlist = py310, py311, py312, py313
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    requests
    mako
    mdformat
    pydantic-settings
    pre-commit
commands =
    pytest tests/
    mdformat --check .
